---
title: "Ensemble genome builds"
author: "Pedro Batista Tan."
date: "`r strftime(Sys.Date(), '%B %d %Y')`"
output: 
  html_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning=FALSE, message = FALSE
  # dpi = 300, fig.width = 10, fig.height = 6
)

# install.packages("tidyverse")
library(tidyverse)
```

```{r}
# Reference vignette tutorial
# https://www.bioconductor.org/packages/devel/bioc/vignettes/ensembldb/inst/doc/ensembldb.html

#BiocManager::install("EnsDb.Hsapiens.v86")
library(EnsDb.Hsapiens.v86)
edb <- EnsDb.Hsapiens.v86

organism(edb)
supportedFilters(edb)
listTxbiotypes(edb)
listTables(edb)
```
```{r}
ensembl_db <- genes(edb, return.type = "DataFrame")
ensembl_db <- ensembl_db %>% as.data.frame()


# Unlist entreiz column to export as csv
entrezids <- data.frame(matrix(unlist(ensembl_db$entrezid), nrow=length(ensembl_db$entrezid), byrow=TRUE))

entrezids <- entrezids %>% rename("entrezid_1" = "X1", "entrezid_2" = "X2")

# Remove entrezid "list" column and add the unlisted columns
ensembl_db_c <- ensembl_db %>% dplyr::select(-entrezid) %>% cbind(entrezids)

# Export ensembl df
ensembl_db_c %>%  write_csv("EnsDb.Hsapiens.v86.csv")

#edb_rRNA <- edb %>% filter(filter = ~tx_biotype == c("rRNA", "Mt_rRNA"))
#edb_rRNA <- genes(edb_rRNA, return.type = "DataFrame")
#rRNA_df <- edb_rRNA %>% as.data.frame()
#rRNA_df %>% write_csv("rRNA_df.csv")
```