---
title: "Bakhoum et al 2018 scRNA-seq"
author: "Pedro Batista Tan"
date: "`r strftime(Sys.Date(), '%B %d %Y')`"
output: 
  html_document:
    toc: true
    number_sections: true
params:
  export: TRUE
---
# Loading Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, warning=FALSE, message = FALSE, dpi = 300
  # fig.width = 10, fig.height = 6, output: html_notebook
)

# install.packages("BiocManager") #(only if you do not have BiocManager)
#BiocManager::install("DropletUtils")
# install.packages("Seurat", "tidyverse")
library(Seurat)
library(tidyverse)

set.seed(42)
select = dplyr::select
rename = dplyr::rename
```

# Setup
```{r Setup}
export = params$export

# generate output dir path named data
source.output.dir <- file.path("output_sc")

# if source output dir does not exist, create it
if (!dir.exists(source.output.dir)) {
    dir.create(source.output.dir)
} else{
  print("Output folder already exists")
}

```

# Loading data
```{r}
data_dir <- 'data/CINdata/Kif2b/'
list.files(data_dir) # Should show barcodes.tsv, genes.tsv, and matrix.mtx
kif2b_expression_matrix <- Read10X(data.dir = data_dir)
kif2b = CreateSeuratObject(counts = kif2b_expression_matrix, project = "kif2b")

data_dir <- 'data/CINdata/MCAK/'
MCAK_expression_matrix <- Read10X(data.dir = data_dir)
MCAK = CreateSeuratObject(counts = MCAK_expression_matrix, project = "MCAK")

data_dir <- 'data/CINdata/MCAK-Hypir/'
dnMCAK_expression_matrix <- Read10X(data.dir = data_dir)
dnMCAK = CreateSeuratObject(counts = dnMCAK_expression_matrix, project = "dnMCAK")

# Remove objects to free memory and clean up workspace 
rm(kif2b_expression_matrix)
rm(MCAK_expression_matrix)
rm(dnMCAK_expression_matrix)
rm(data_dir)
rm(source.output.dir)
```

# Inspecting dataset, QC plots
```{r}
str_detect(rownames(kif2b), "^MT-") %>% sum()
str_detect(rownames(MCAK), "^MT-") %>% sum()
str_detect(rownames(dnMCAK), "^MT-") %>% sum()
```

```{r}
# Compute the % of mitochondrial counts
kif2b[["percent.mt"]] <- PercentageFeatureSet(kif2b, pattern = "^MT-") %>% mutate_all(~replace(., is.na(.), 0))
MCAK[["percent.mt"]] <- PercentageFeatureSet(MCAK, pattern = "^MT-") %>% mutate_all(~replace(., is.na(.), 0))
dnMCAK[["percent.mt"]] <- PercentageFeatureSet(dnMCAK, pattern = "^MT-") %>% mutate_all(~replace(., is.na(.), 0))
```

```{r}
# QC plots based on number of counts, features and % of mitochondrial genes
VlnPlot(kif2b, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
VlnPlot(MCAK, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
VlnPlot(dnMCAK, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

FeatureScatter(kif2b, feature1 = "nCount_RNA", feature2 = "percent.mt") +
FeatureScatter(kif2b, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

FeatureScatter(MCAK, feature1 = "nCount_RNA", feature2 = "percent.mt") +
FeatureScatter(MCAK, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

FeatureScatter(dnMCAK, feature1 = "nCount_RNA", feature2 = "percent.mt") +
FeatureScatter(dnMCAK, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

kif2b@meta.data %>% select(nCount_RNA, nFeature_RNA, percent.mt) %>% summary()
MCAK@meta.data %>% select(nCount_RNA, nFeature_RNA, percent.mt) %>% summary()
dnMCAK@meta.data %>% select(nCount_RNA, nFeature_RNA, percent.mt) %>% summary()


```

# Filter datasets
```{r}
# Filter dataset based on # of features, counts and mitocondrial %
kif2b_f <- subset(kif2b, subset = nFeature_RNA > 200 & percent.mt < 25 & nCount_RNA > 5000)
MCAK_f <- subset(MCAK, subset = nFeature_RNA > 200 & percent.mt < 25 & nCount_RNA > 5000)
dnMCAK_f <- subset(dnMCAK, subset = nFeature_RNA > 200 & percent.mt < 25 & nCount_RNA > 5000)

kif2b_f
MCAK_f
dnMCAK_f

nrow(kif2b_f@meta.data) + nrow(MCAK_f@meta.data) + nrow(dnMCAK_f@meta.data)
```

```{r}
# QC plots after filtering
VlnPlot(kif2b_f, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
VlnPlot(MCAK_f, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
VlnPlot(dnMCAK_f, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

FeatureScatter(kif2b_f, feature1 = "nCount_RNA", feature2 = "percent.mt") +
FeatureScatter(kif2b_f, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

FeatureScatter(MCAK_f, feature1 = "nCount_RNA", feature2 = "percent.mt") +
FeatureScatter(MCAK_f, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

FeatureScatter(dnMCAK_f, feature1 = "nCount_RNA", feature2 = "percent.mt") +
FeatureScatter(dnMCAK_f, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")


kif2b_f@meta.data %>% select(nCount_RNA, nFeature_RNA, percent.mt) %>% summary()
MCAK_f@meta.data %>% select(nCount_RNA, nFeature_RNA, percent.mt) %>% summary()
dnMCAK_f@meta.data %>% select(nCount_RNA, nFeature_RNA, percent.mt) %>% summary()

```

```{r}
# Remove objects to free memory and clean up workspace 
rm(kif2b)
rm(MCAK)
rm(dnMCAK)
```

# Combine datasets
```{r}
# Combine datasets
Seurat_object <- merge(kif2b_f, y = c(MCAK_f, dnMCAK_f), add.cell.ids = c("kif2b", "MCAK", "dnMCAK"), project = "BakhoumEtAl2018")

Seurat_object

colnames(Seurat_object) %>% head()
colnames(Seurat_object) %>% tail()
```

# Edit metadata
```{r}
colnames(Seurat_object[[]])
```

```{r}
Seurat_object@meta.data <- Seurat_object[[]] %>% mutate(Project = "BakhoumEtAl2018", Sample = orig.ident)
```

## Annotation for inferCNV
```{r}
annot_scRNA <- Seurat_object@meta.data %>% mutate(
  annotation = Sample)

table(annot_scRNA$annotation)

Seurat_object@meta.data$annotation <- annot_scRNA$annotation

# Write annotations file
Seurat_object@meta.data %>% select(annotation) %>% rownames_to_column("sample_id") %>% write.table(file = "cellAnnotations.txt", sep = "\t", row.names = FALSE, col.names = FALSE)

ref_group_names <- Seurat_object@meta.data %>% select(annotation) %>% unique() %>% filter(annotation %in% c("kif2b", "MCAK"))

ref_group_names %>% write.csv2(file = "ref_group_names.csv", row.names = FALSE)
```

# Export
```{r}
saveRDS(Seurat_object, file = file.path(source.output.dir, "Seurat_object.rds"))

# Seurat_object <- readRDS(file = file.path(source.output.dir, "Seurat_object.rds"))
```
