---
title: "Lee et al 2020 scRNA-seq"
author: "Pedro Batista Tan"
date: "`r strftime(Sys.Date(), '%B %d %Y')`"
output: 
  html_document:
    toc: true
    number_sections: true
params:
  export: TRUE
---
# Loading Packages
```{r setup, include=TRUE}
knitr::opts_chunk$set(
  echo = TRUE, warning=FALSE, message = FALSE, dpi = 300, error = TRUE
  # fig.width = 10, fig.height = 6, output: html_notebook
)

# install.packages("BiocManager") #(only if you do not have BiocManager)
# BiocManager::install("DropletUtils", "org.Hs.eg.db")
# install.packages("Seurat", "sparseMatrixStats", "tidyverse")
library(Seurat)
library(sparseMatrixStats)
library(tidyverse)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(plotly)

source(paste0(dirname(getwd()), "/Helper_functions.R"))

select = dplyr::select

```

# Setup
```{r Setup}
export = params$export

Seurat_object_name <- "scLee"

# generate output dir path named data
source.output.dir <- file.path("output_sc")

# if source output dir does not exist, create it
if (!dir.exists(source.output.dir)) {
    dir.create(source.output.dir)
} else{
  print("Output folder already exists")
}

```

# Loading data
```{r}
design <- read.table("data/ExpDesign-E-MTAB-8410.tsv", sep = "\t", header = TRUE)

study_metadata = read.table(file = "data/E-MTAB-8410.sdrf.txt", header = TRUE, sep = "\t")
```

```{r}
colnames(design)
metadata <- design %>% select(-c(Sample.Characteristic.Ontology.Term.organism., Sample.Characteristic.Ontology.Term.age., Sample.Characteristic.Ontology.Term.developmental.stage., Sample.Characteristic.Ontology.Term.sex., Sample.Characteristic.Ontology.Term.individual., Sample.Characteristic.Ontology.Term.organism.part., Sample.Characteristic.Ontology.Term.sampling.site., Factor.Value.Ontology.Term.sampling.site., Factor.Value.Ontology.Term.inferred.cell.type...authors.labels., Factor.Value.Ontology.Term.inferred.cell.type...ontology.labels.))

summary(metadata %>% mutate_if(is.character, as.factor))
```

```{r}
KUL_data <- read.table("data/GSE144735_processed_KUL3_CRC_10X_raw_UMI_count_matrix.txt", header = TRUE)
KUL_metadata <- read.table("data/GSE144735_processed_KUL3_CRC_10X_annotation.txt", sep = "\t", header = TRUE)
KUL_metadata <- KUL_metadata %>% mutate_if(is.character, as.factor)

head(KUL_data, 20)
row.names(KUL_data) <- c()
KUL_data <- KUL_data %>% column_to_rownames("Index")

data = as.matrix(KUL_data)
rm(KUL_data)

data = as(data, "dgCMatrix")
scLee_KUL = CreateSeuratObject(counts = data, project = "LeeEtAl2020_KUL")
rm(data)

scLee_KUL@meta.data <- scLee_KUL@meta.data %>% rownames_to_column("Index") %>% left_join(KUL_metadata, by = "Index") %>% column_to_rownames("Index")

saveRDS(scLee_KUL, file = paste0(source.output.dir, "/scLee_KUL.rds"))
# scLee_KUL <- readRDS(file = paste0(source.output.dir, "/scLee_KUL.rds"))

```

```{r}
SMC_data <- read.table("data/GSE132465_GEO_processed_CRC_10X_raw_UMI_count_matrix.txt", sep = "\t", header = TRUE)
SMC_metadata <- read.table("data/GSE132465_GEO_processed_CRC_10X_cell_annotation.txt", sep = "\t", header = TRUE)
SMC_metadata <- SMC_metadata %>% mutate_if(is.character, as.factor)

head(SMC_data, 20)
row.names(SMC_data) <- c()

SMC_data <- SMC_data %>% column_to_rownames("Index")

data = as.matrix(SMC_data)
rm(SMC_data)

data = as(data, "dgCMatrix")
scLee_SMC = CreateSeuratObject(counts = data, project = "LeeEtAl2020_SMC")
rm(data)

SMC_metadata$Index <- gsub("-", ".", SMC_metadata$Index)

scLee_SMC@meta.data <- scLee_SMC@meta.data %>% rownames_to_column("Index") %>% left_join(SMC_metadata, by = "Index") %>% column_to_rownames("Index")

saveRDS(scLee_SMC, file = paste0(source.output.dir, "/scLee_SMC.rds"))
# scLee_SMC <- readRDS(file = paste0(source.output.dir, "/scLee_SMC.rds"))
```

```{r}
summary(KUL_metadata)
table(KUL_metadata$Cell_type)
table(KUL_metadata$Cell_subtype)

table(KUL_metadata$Cell_type, KUL_metadata$Cell_subtype)
table(KUL_metadata$Cell_subtype, KUL_metadata$Cell_type)
table(KUL_metadata$Patient, KUL_metadata$Cell_subtype)
```

```{r}
summary(SMC_metadata)

table(SMC_metadata$Cell_type)
table(SMC_metadata$Cell_subtype)

table(SMC_metadata$Cell_type, SMC_metadata$Cell_subtype)
table(SMC_metadata$Cell_subtype, SMC_metadata$Cell_type)
table(SMC_metadata$Patient, SMC_metadata$Cell_subtype)

```

```{r}
Seurat_object <- merge(scLee_KUL, y = scLee_SMC, project = "LeeEtAl2020")
rm(scLee_KUL, scLee_SMC)

saveRDS(Seurat_object, file = paste0(source.output.dir, "/", Seurat_object_name, "_c.rds"))

# Seurat_object <- readRDS(file = paste0(source.output.dir, "/", Seurat_object_name, "_c.rds"))
```

# Inspecting dataset, QC plots
```{r}
# Check whether mitochondrial genes are present in the samples
rownames(Seurat_object)[str_detect(rownames(Seurat_object), "^MT-")]

# Compute the % of mitochondrial counts
Seurat_object[["percent.mt"]] <- PercentageFeatureSet(Seurat_object, pattern = "^MT-") %>% mutate_all(~replace(., is.na(.), 0))
```

```{r}
Idents(Seurat_object) <- "Patient"

# QC plots based on number of counts, features and % of mitochondrial genes
VlnPlot(Seurat_object, features = c("nFeature_RNA"))
VlnPlot(Seurat_object, features = c("nCount_RNA"))
VlnPlot(Seurat_object, features = c("percent.mt"))

FeatureScatter(Seurat_object, feature1 = "nCount_RNA", feature2 = "percent.mt") 
FeatureScatter(Seurat_object, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

Seurat_object@meta.data %>% select(nCount_RNA, nFeature_RNA, percent.mt) %>% summary()
```
# Edit metadata
```{r}
colnames(Seurat_object[[]])
table(Seurat_object$orig.ident)
table(Seurat_object$Patient)
table(Seurat_object$Class)
table(Seurat_object$Cell_type)
table(Seurat_object$Cell_subtype)
table(Seurat_object$Cell_subtype, Seurat_object$Cell_type)
```

```{r}
Seurat_object@meta.data <- Seurat_object[[]] %>% rename("Sample.orig" = Sample) %>% mutate(Project = "LeeEtAl2020", Sample = Patient)
```

```{r}
simpler_labels <- Seurat_object@meta.data %>% select(Cell_type, Cell_subtype) %>% unique()

simpler_labels <- simpler_labels %>% mutate(Simplified_celltype = ifelse(Cell_subtype %in% c("CMS1","CMS2","CMS3","CMS4"), "tumor", Cell_type))

simpler_celltype_metadata <- Seurat_object@meta.data %>% left_join(simpler_labels, by = c("Cell_type", "Cell_subtype"))

Seurat_object@meta.data$Simplified_celltype <- simpler_celltype_metadata$Simplified_celltype
```

## Annotation for inferCNV
```{r}
annot_scRNA <- Seurat_object@meta.data %>% select(Cell_subtype, Simplified_celltype, Patient) %>% mutate(
  Cell_class = ifelse(str_detect(Simplified_celltype, "tumor"), "tumor", Simplified_celltype),
  annotation = ifelse(Cell_class == "tumor", paste0(Cell_class, "_", Patient), Cell_class))

annot_scRNA %>% mutate_if(is.character, as.factor) %>% summary()
table(annot_scRNA$annotation)

Seurat_object@meta.data$annotation <- annot_scRNA$annotation
Seurat_object@meta.data$Cell_class <- annot_scRNA$Cell_class

table(annot_scRNA$annotation)
table(annot_scRNA$Cell_class)

# Write annotations file
Seurat_object@meta.data %>% filter(Simplified_celltype %in% c("tumor", "Epithelial cells")) %>% select(annotation) %>% rownames_to_column("sample_id") %>% write.table(file = "cellAnnotations.txt", sep = "\t", row.names = FALSE, col.names = FALSE)

ref_group_names <- Seurat_object@meta.data %>% filter(Simplified_celltype %in% c("tumor", "Epithelial cells")) %>% select(annotation) %>% unique() %>% filter(!str_detect(annotation, "tumor"))

ref_group_names %>% write.csv2(file = "ref_group_names.csv", row.names = FALSE)
```

```{r}
table(Seurat_object$Simplified_celltype)
table(Seurat_object$Simplified_celltype, Seurat_object$Patient)
table(Seurat_object$Simplified_celltype, Seurat_object$Class)

prop.table(table(Seurat_object$Simplified_celltype, Seurat_object$Patient), margin = 2)
```

# Export
```{r}
saveRDS(Seurat_object, file = paste0(source.output.dir, "/Seurat_object.rds"))

# Seurat_object <- readRDS(file = paste0(source.output.dir, "/Seurat_object.rds"))
```

# sessionInfo - Package Versions
```{r}
sessionInfo()
# packageVersion("DESeq2")
# packinfo <- installed.packages(fields = c("Package", "Version"))
# packinfo[,c("Package", "Version")]
# packinfo["graphics",c("Package", "Version")]
```

